
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: mensetusiyoyo_development

# test:
#   <<: *default
#   database: mensetusiyoyo_test


# production:
#   <<: *default
#   database: mensetusiyoyo_production
#   username: mensetusiyoyo
#   password: <%= ENV["MENSETUSIYOYO_DATABASE_PASSWORD"] %>


efault: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: mensetusiyoyo_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: mensetusiyoyo_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>